### ISSUE TITLE
Doesn't work for microsoft.com

### ISSUE THREAD

**Issue by johnotander** [cssstats/get-css#13]
I suspect it's a result of not following redirects.

**Comment by hoffi** [comment]
`getcss microsoft.com > ms.css` works for me. 
Also `request` follows 3xx redirects by default.

**Comment by johnotander** [comment]
Yeah, that's what was confusing to me, since `request` will gladly follow any `3xx` redirect. However, I was able to verify that this url does work now, so I'll go ahead and close this. Thanks!
