### ISSUE TITLE
Handle URLs to CSS files

### ISSUE THREAD

**Issue by hoffi** [cssstats/get-css#23]
Shouldn't this module also handle URLs that point directly to css files?

Actually this is handled in [cssstats: resource.js](https://github.com/cssstats/cssstats/blob/master/services/resource.js#L9)

IMHO this should use the same `request` command like in `get-css`

**Comment by johnotander** [comment]
Undoubtedly. We can leverage the [`is-css`](https://github.com/cssstats/is-css) module to handle this case.
