### ISSUE TITLE
Not working on www.getnoodl.es

### ISSUE THREAD

**Issue by lachlanjc** [cssstats/get-css#32]
Trying to use get-css on my own app, [Noodles](http://www.getnoodl.es/). The login page (http://www.getnoodl.es/login) has the whole application's CSS, but get-css returns `Error: getaddrinfo ENOTFOUND getnoodl.es` on it.

**Comment by johnotander** [comment]
Hey, thanks for reporting this! It looks like it's a bug with the url normalization. Currently, we've failed to specify [stripWWW: false](https://github.com/sindresorhus/normalize-url#stripwww) so the url is being changed from www.getnoodl.es to getnoodl.es which doesn't resolve. I should have a PR in by the end of the day.

**Comment by johnotander** [comment]
```sh
$ npm i -g get-css
$ getcss www.noodl.es
```

**Comment by lachlanjc** [comment]
Awesome, thanks for the quick fix on that! We should get that merged into cssstats-core as well.

**Comment by johnotander** [comment]
This has now been added to cssstats and deployed to cssstats.com : )

**Comment by lachlanjc** [comment]
Awesome! Thanks.
